"""empty message

Revision ID: 01137b025859
Revises: 82539f5016b2
Create Date: 2025-04-28 12:34:44.328239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01137b025859'
down_revision = '82539f5016b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_ocurrencia', sa.DateTime(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.Column('numero_reporte', sa.String(length=100), nullable=True),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADO', 'CANCELADO', name='estatusactividad'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultima_modificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades_proveedor')
    # ### end Alembic commands ###
