"""empty message

Revision ID: 0650f26ae3ca
Revises: 9733fdcded0c
Create Date: 2024-06-03 21:35:29.329726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0650f26ae3ca'
down_revision = '9733fdcded0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.drop_column('contract')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
