"""empty message

Revision ID: 53fdb61acd77
Revises: 7e281f116d7e
Create Date: 2025-09-05 12:27:27.111526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fdb61acd77'
down_revision = '7e281f116d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extintores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False, comment='Tag o ID único del extintor'),
    sa.Column('piso', sa.String(length=50), nullable=False, comment="Piso donde se encuentra, ej: 'Piso 1', 'PB', 'Azotea'"),
    sa.Column('ubicacion_exacta', sa.String(length=255), nullable=False, comment="Descripción textual de la ubicación, ej: 'Pasillo A, al lado de la puerta'"),
    sa.Column('tipo', sa.String(length=50), nullable=False, comment="Tipo de extintor, ej: 'PQS', 'CO2', 'Agua'"),
    sa.Column('capacidad_kg', sa.Float(), nullable=False, comment='Capacidad en kilogramos o litros'),
    sa.Column('fecha_fabricacion', sa.Date(), nullable=True),
    sa.Column('fecha_ultima_recarga', sa.Date(), nullable=False),
    sa.Column('fecha_proxima_recarga', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False, comment='Ej: Operativo, Vencido, Obstruido, Faltante'),
    sa.Column('coordenada_x', sa.Integer(), nullable=True, comment='Posición X en píxeles en el mapa del piso'),
    sa.Column('coordenada_y', sa.Integer(), nullable=True, comment='Posición Y en píxeles en el mapa del piso'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('mapas_pisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_piso', sa.String(length=100), nullable=False),
    sa.Column('nombre_archivo_original', sa.String(length=255), nullable=False),
    sa.Column('datos_archivo', sa.LargeBinary(), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_piso')
    )
    op.create_table('revisiones_extintor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extintor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_revision', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('realizado_por', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['extintor_id'], ['extintores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contactos_proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_contacto', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos_proveedor', schema=None) as batch_op:
        batch_op.drop_column('nombre_contacto')

    op.drop_table('revisiones_extintor')
    op.drop_table('mapas_pisos')
    op.drop_table('extintores')
    # ### end Alembic commands ###
