"""empty message

Revision ID: 68504302de75
Revises: 868b92ee33f0
Create Date: 2025-05-13 13:33:22.357084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68504302de75'
down_revision = '868b92ee33f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alertas_resueltas_info', sa.Text(), nullable=True, comment='Información sobre las alertas que este mantenimiento resolvió'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.drop_column('alertas_resueltas_info')

    # ### end Alembic commands ###
