"""empty message

Revision ID: 6b38eaa25f87
Revises: b3fd9a71e1a0
Create Date: 2025-05-12 10:28:49.107369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b38eaa25f87'
down_revision = 'b3fd9a71e1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturas', schema=None) as batch_op:
        batch_op.alter_column('humedad',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturas', schema=None) as batch_op:
        batch_op.alter_column('humedad',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
