"""empty message

Revision ID: 7e281f116d7e
Revises: 
Create Date: 2025-05-30 11:06:20.375736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e281f116d7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aires_acondicionados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True, comment='Ubicación general del equipo completo'),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True, comment='Tipo de aire (confort, precision, etc.)'),
    sa.Column('toneladas', sa.Float(), nullable=True, comment='Capacidad en toneladas de refrigeración'),
    sa.Column('evaporadora_operativa', sa.Enum('OPERATIVA', 'PARCIALMENTE_OPERATIVA', 'NO_OPERATIVA', name='operativastateenum'), nullable=False, comment='Estado operativo actual de la evaporadora'),
    sa.Column('evaporadora_marca', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_modelo', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_serial', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_codigo_inventario', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_ubicacion_instalacion', sa.String(length=200), nullable=True, comment='Ubicación específica de la evaporadora'),
    sa.Column('condensadora_operativa', sa.Enum('OPERATIVA', 'PARCIALMENTE_OPERATIVA', 'NO_OPERATIVA', name='operativastateenum'), nullable=False, comment='Estado operativo de la condensadora'),
    sa.Column('condensadora_marca', sa.String(length=100), nullable=True),
    sa.Column('condensadora_modelo', sa.String(length=100), nullable=True),
    sa.Column('condensadora_serial', sa.String(length=100), nullable=True),
    sa.Column('condensadora_codigo_inventario', sa.String(length=100), nullable=True),
    sa.Column('condensadora_ubicacion_instalacion', sa.String(length=200), nullable=True, comment='Ubicación específica de la condensadora'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('serial', sa.String(length=120), nullable=False),
    sa.Column('partNumber', sa.String(length=120), nullable=True),
    sa.Column('five_years_prevition', sa.String(length=255), nullable=True),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.Column('componentType', sa.String(length=100), nullable=False),
    sa.Column('requestType', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostico_componente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('parte_ac', sa.Enum('EVAPORADORA', 'CONDENSADORA', 'GENERAL', name='parteacenum'), nullable=False),
    sa.Column('tipo_aire_sugerido', sa.Enum('CONFORT', 'PRECISION', 'AMBOS', name='tipoairerelevanteenum'), nullable=False),
    sa.Column('descripcion_ayuda', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('otros_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo del equipo'),
    sa.Column('tipo', sa.String(length=50), nullable=False, comment='Tipo de equipo (Motogenerador, UPS, PDU, etc.)'),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('codigo_inventario', sa.String(length=100), nullable=True),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('estado_operativo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True, comment='Información adicional relevante'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email_proveedor', sa.String(length=120), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tracker_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_conexion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('coordination', sa.String(length=120), nullable=False),
    sa.Column('clientName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_ocurrencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.Column('numero_reporte', sa.String(length=100), nullable=True),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADO', 'CANCELADO', name='estatusactividad'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tracker_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=120), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_externo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nombre_archivo_original', sa.String(length=255), nullable=False),
    sa.Column('datos_archivo', sa.LargeBinary(), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('usuario_carga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_carga_id'], ['tracker_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aire_id', sa.Integer(), nullable=True),
    sa.Column('otro_equipo_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('humedad', sa.Float(), nullable=True),
    sa.CheckConstraint('(aire_id IS NOT NULL AND otro_equipo_id IS NULL) OR (aire_id IS NULL AND otro_equipo_id IS NOT NULL)', name='chk_lectura_device_exclusive'),
    sa.ForeignKeyConstraint(['aire_id'], ['aires_acondicionados.id'], ),
    sa.ForeignKeyConstraint(['otro_equipo_id'], ['otros_equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aire_id', sa.Integer(), nullable=True),
    sa.Column('otro_equipo_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_mantenimiento', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tecnico', sa.String(length=100), nullable=True),
    sa.Column('imagen_nombre', sa.String(length=255), nullable=True),
    sa.Column('imagen_tipo', sa.String(length=50), nullable=True),
    sa.Column('imagen_datos', sa.LargeBinary(), nullable=True),
    sa.Column('alertas_resueltas_info', sa.Text(), nullable=True, comment='Información sobre las alertas que este mantenimiento resolvió'),
    sa.CheckConstraint('(aire_id IS NOT NULL AND otro_equipo_id IS NULL) OR (aire_id IS NULL AND otro_equipo_id IS NOT NULL)', name='chk_mantenimiento_target'),
    sa.ForeignKeyConstraint(['aire_id'], ['aires_acondicionados.id'], ),
    sa.ForeignKeyConstraint(['otro_equipo_id'], ['otros_equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('has_cabinet', sa.Boolean(), nullable=True),
    sa.Column('leased', sa.Boolean(), nullable=True),
    sa.Column('total_cabinets', sa.String(length=10), nullable=True),
    sa.Column('open_closed', sa.Boolean(), nullable=True),
    sa.Column('security', sa.Boolean(), nullable=True),
    sa.Column('type_security', sa.String(length=50), nullable=True),
    sa.Column('has_extractors', sa.Boolean(), nullable=True),
    sa.Column('extractors_ubication', sa.String(length=50), nullable=True),
    sa.Column('modular', sa.Boolean(), nullable=True),
    sa.Column('lateral_doors', sa.Boolean(), nullable=True),
    sa.Column('lateral_ubication', sa.String(length=50), nullable=True),
    sa.Column('rack_unit', sa.String(length=10), nullable=True),
    sa.Column('rack_position', sa.String(length=120), nullable=True),
    sa.Column('rack_ubication', sa.String(length=50), nullable=True),
    sa.Column('has_accessory', sa.Boolean(), nullable=True),
    sa.Column('accessory_description', sa.String(length=50), nullable=True),
    sa.Column('rack_width', sa.String(length=10), nullable=True),
    sa.Column('rack_length', sa.String(length=10), nullable=True),
    sa.Column('rack_height', sa.String(length=10), nullable=True),
    sa.Column('internal_pdu', sa.String(length=10), nullable=True),
    sa.Column('input_connector', sa.String(length=100), nullable=True),
    sa.Column('fases', sa.String(length=10), nullable=True),
    sa.Column('output_connector', sa.String(length=20), nullable=True),
    sa.Column('neutro', sa.Boolean(), nullable=True),
    sa.Column('description_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['description.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_diagnostico_aire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aire_id', sa.Integer(), nullable=False),
    sa.Column('parte_ac', sa.Enum('EVAPORADORA', 'CONDENSADORA', 'GENERAL', name='parteacenum'), nullable=False),
    sa.Column('diagnostico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('registrado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('solucionado', sa.Boolean(), nullable=False),
    sa.Column('fecha_solucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aire_id'], ['aires_acondicionados.id'], ),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['diagnostico_componente.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_usuario_id'], ['tracker_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umbrales_configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aire_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('es_global', sa.Boolean(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('hum_min', sa.Float(), nullable=False),
    sa.Column('hum_max', sa.Float(), nullable=False),
    sa.Column('notificar_activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aire_id'], ['aires_acondicionados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_width', sa.String(length=120), nullable=True),
    sa.Column('equipment_height', sa.String(length=120), nullable=True),
    sa.Column('equipment_length', sa.String(length=120), nullable=True),
    sa.Column('packaging_width', sa.String(length=120), nullable=True),
    sa.Column('packaging_length', sa.String(length=120), nullable=True),
    sa.Column('packaging_height', sa.String(length=120), nullable=True),
    sa.Column('weight', sa.String(length=120), nullable=True),
    sa.Column('anchor_type', sa.String(length=120), nullable=True),
    sa.Column('service_area', sa.Boolean(), nullable=True),
    sa.Column('service_frontal', sa.Boolean(), nullable=True),
    sa.Column('service_back', sa.Boolean(), nullable=True),
    sa.Column('service_lateral', sa.Boolean(), nullable=True),
    sa.Column('access_width', sa.String(length=120), nullable=True),
    sa.Column('access_inclination', sa.String(length=120), nullable=True),
    sa.Column('access_length', sa.String(length=120), nullable=True),
    sa.Column('rack_number', sa.String(length=10), nullable=True),
    sa.Column('equip_rack_ubication', sa.String(length=10), nullable=True),
    sa.Column('rack_unit_position', sa.String(length=120), nullable=True),
    sa.Column('total_rack_units', sa.String(length=10), nullable=True),
    sa.Column('ac_dc', sa.String(length=10), nullable=True),
    sa.Column('input_current', sa.String(length=50), nullable=True),
    sa.Column('power', sa.String(length=20), nullable=True),
    sa.Column('power_supply', sa.String(length=20), nullable=True),
    sa.Column('operation_temp', sa.String(length=20), nullable=True),
    sa.Column('thermal_disipation', sa.String(length=20), nullable=True),
    sa.Column('power_config', sa.String(length=20), nullable=True),
    sa.Column('description_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['description_id'], ['description.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('umbrales_configuracion')
    op.drop_table('registros_diagnostico_aire')
    op.drop_table('rack')
    op.drop_table('mantenimientos')
    op.drop_table('lecturas')
    op.drop_table('documento_externo')
    op.drop_table('contactos_proveedor')
    op.drop_table('audit_logs')
    op.drop_table('actividades_proveedor')
    op.drop_table('user_form')
    op.drop_table('tracker_usuarios')
    op.drop_table('proveedores')
    op.drop_table('otros_equipos')
    op.drop_table('diagnostico_componente')
    op.drop_table('description')
    op.drop_table('aires_acondicionados')
    # ### end Alembic commands ###
