"""empty message

Revision ID: 82539f5016b2
Revises: 29ffc380e1d0
Create Date: 2025-04-28 11:54:23.083517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82539f5016b2'
down_revision = '29ffc380e1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email_proveedor', sa.String(length=120), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('contactos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=150), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=120), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aires_acondicionados', schema=None) as batch_op:
        batch_op.drop_constraint('aires_acondicionados_condensadora_codigo_inventario_key', type_='unique')
        batch_op.drop_constraint('aires_acondicionados_condensadora_serial_key', type_='unique')
        batch_op.drop_constraint('aires_acondicionados_evaporadora_codigo_inventario_key', type_='unique')
        batch_op.drop_constraint('aires_acondicionados_evaporadora_serial_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aires_acondicionados', schema=None) as batch_op:
        batch_op.create_unique_constraint('aires_acondicionados_evaporadora_serial_key', ['evaporadora_serial'])
        batch_op.create_unique_constraint('aires_acondicionados_evaporadora_codigo_inventario_key', ['evaporadora_codigo_inventario'])
        batch_op.create_unique_constraint('aires_acondicionados_condensadora_serial_key', ['condensadora_serial'])
        batch_op.create_unique_constraint('aires_acondicionados_condensadora_codigo_inventario_key', ['condensadora_codigo_inventario'])

    op.drop_table('contactos_proveedor')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
