"""empty message

Revision ID: 8484182de6d7
Revises: 0650f26ae3ca
Create Date: 2024-06-09 11:32:00.479360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8484182de6d7'
down_revision = '0650f26ae3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requestType', sa.String(length=50), nullable=True))
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('requestType')

    # ### end Alembic commands ###
