"""empty message

Revision ID: 868b92ee33f0
Revises: ee9517a66754
Create Date: 2025-05-13 12:36:53.444428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868b92ee33f0'
down_revision = 'ee9517a66754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aires_acondicionados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaporadora_fecha_hora_diagnostico', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora en que se registró el diagnóstico de la evaporadora'))
        batch_op.add_column(sa.Column('condensadora_fecha_hora_diagnostico', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora en que se registró el diagnóstico de la condensadora'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aires_acondicionados', schema=None) as batch_op:
        batch_op.drop_column('condensadora_fecha_hora_diagnostico')
        batch_op.drop_column('evaporadora_fecha_hora_diagnostico')

    # ### end Alembic commands ###
