"""empty message

Revision ID: 8bd73f4208e8
Revises: 8484182de6d7
Create Date: 2024-06-09 12:23:09.212649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd73f4208e8'
down_revision = '8484182de6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partNumber', sa.String(length=120), nullable=True))
        batch_op.drop_column('number_part')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_part', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('partNumber')

    # ### end Alembic commands ###
