"""empty message

Revision ID: b3fd9a71e1a0
Revises: 8cc3458463a4
Create Date: 2025-04-29 14:13:05.468208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fd9a71e1a0'
down_revision = '8cc3458463a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_externo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nombre_archivo_original', sa.String(length=255), nullable=False),
    sa.Column('datos_archivo', sa.LargeBinary(), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('usuario_carga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_carga_id'], ['tracker_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento_externo')
    # ### end Alembic commands ###
